@startuml
'https://plantuml.com/class-diagram

hide circle
allowmixing

class Gateway <<domain>> <<ably app>> <<service>> {
  appMasterKey <<secret>>
}

Gateway *-- "*" Account

class Account <<abstract>> <<subject>> {
  vf:primaryAccountable : IRI [1..*]
  timesheet : IRI [*]
  project : Project [*]
}

Account *--> "*" Timesheet: owns

Account *--> "*" Project: owns

class UserAccount {
  email : string [*]
  keyid : string [*]
}
note left of UserAccount::email
  Registered email, used
  for account activation
end note
note left of UserAccount::keyid
  Matches ""ably.key""
  Can be revoked
end note
UserAccount --|> Account

class OrganisationAccount {
  foaf:member : UserAccount [*]
}
note left of OrganisationAccount::foaf:member
  Only user accounts:
  no org hierarchy
end note
OrganisationAccount --|> Account
OrganisationAccount o-- "1..*" UserAccount

class Timesheet <<domain>> {
  account<sub>t</sub> : Account
}
note right of Timesheet
  not actually a subject
  in the Gateway domain
end note

class Project <<subject>> {
  vf:provider : IRI [*]
  timesheet : Timesheet [*]
}

Project "*" -- "*" Timesheet

component CLI [
  CLI

  ---
  ably.key <<secret>>
  account<sub>u</sub> (aka principal.@id)
  timesheets : domain [*]
]
note top of CLI
  Installed on a device
  under an OS account.
  Registered to user account
  via ably.key.
end note

UserAccount .. "*" CLI

CLI ..> "*" Timesheet: entailed write access to timesheets
note bottom on link
  account<sub>u</sub> = account<sub>t</sub>
  ∨
  ∃project:Project ⦁
    timesheet ∈ project.timesheet
    ∧ (
      account<sub>u</sub> ∈ project.vf:provider
      ∨
      ∃org:OrganisationAccount ⦁
        org ∈ project.vf:provider ∧
        account<sub>u</sub> ∈ org.foaf:member
    )
end note

package Ably <<service>> {
  class AblyKey {
    keyid
    name
    secret
    capabilities : string
  }
  note left of AblyKey::name
    account<sub>u</sub>
  end note
  note left of AblyKey::capabilities
    Defines channel access
    thus, timesheet access
  end note

  UserAccount "1" -- "*" AblyKey
}

@enduml