@startuml
'https://plantuml.com/class-diagram

hide circle
allowmixing

class Gateway <<domain>> <<ably app>> {
  appMasterKey <<secret>>
}

Gateway *-- "*" Account

class Account <<subject>> {
  email: string [*]
  keyid: string [*]
}
note right of Account::keyid
  Matches ""ably.key""
  Can be revoked
end note

Account *--> "*" Timesheet: owns

Account *--> "*" Project: owns

class Timesheet <<domain>> {
}
note right of Timesheet
  not actually a subject
  in the Gateway domain
end note

class Project <<subject>> {
}

Project o-- "*" Account: contributors

Project "*" -- "*" Timesheet

component CLI [
  CLI

  ---
  ably.key <<secret>>
  timesheets: domain [*]
]
note top of CLI
  installed on a device
  under an OS account
end note

Account .. "*" CLI: CLI instance\nregistered to\naccount

CLI ..> "*" Timesheet: entailed access

@enduml