@startuml
'https://plantuml.com/sequence-diagram
hide footbox

User -> CLI ++: open account/timesheet
alt No Ably Key (AbK) or expired
  note over CLI
    configured user is account<sub>u</sub> (required).
    Not always the same as requested timesheet
    account (which may be an organisation).
  end note
  CLI -> User: "pls enter email"
  User --> CLI: email
  CLI -> Gateway ++: jwe(account<sub>u</sub>, email)
  Gateway -> Gateway: If account<sub>u</sub> exists, check\naccount<sub>u</sub> and email match
  Gateway --> CLI: jwt<sub>a</sub> encrypted with code
  note left
    jwt<sub>a</sub> (activation jwt)
    has ⦉ account<sub>u</sub>, email ⦊
    signed with Gateway secret
  end note
  CLI -> User: "pls enter emailed code"
  Gateway --> User --: activation code by email

  User --> CLI: code
  ' TODO: brute force attack (look for a parseable JWT)
  CLI -> CLI: decrypt jwt<sub>a</sub>
  ' TODO: replay attack within JWT validity period
  CLI -> Gateway ++: key(jwt<sub>a</sub>)
  
  Gateway -> Gateway: create Account\nif required
  Gateway <-> Ably: create/update Ably key\n(AbK) & capabilities
  Gateway -> Gateway: generate RSA key\npair for signing\n⦉ SK, PK ⦊
  Gateway -> Gateway: encrypt SK with AbK\n{ SK }<sub>AbK</sub>
  Gateway -> Gateway: ⦉ AbK.id ↦ { SK }<sub>AbK</sub>, PK ⦊\nstored in Account
  return AbK, SK
end

CLI -> Gateway ++: config(account/timesheet, jwt<sub>u</sub>)
note left
  jwt<sub>u</sub> (user jwt) has
  { account<sub>u</sub>, AbK.id }<sub>AbK</sub>
end note
Gateway -> Gateway: check account<sub>u</sub>\ncorresponds to AbK.id
Gateway -> Gateway: check account<sub>u</sub> has\naccess to timesheet
Gateway -> Gateway: update key capability
return config

CLI -> Ably: connect to timesheet channels via m-ld
note over User, CLI: Proceed with session

@enduml