@startuml
'https://plantuml.com/use-case-diagram
left to right direction

actor "User account owner or\nOrganisation acc admin" as user
package "Account administration session" {
  user --> (view account)
  package "User Account" {
    user --> ([list | add | rm] [emails | devices])
  }
  package "Organisation Account" {
    user --> ([list | add | rm] org admins)
  }
  user --> ([list | add | rm] [projects | timesheets])
  user --> (view [project | timesheet])
  user --> ([add | rm] timesheet project link)
}

@enduml