@startuml
'https://plantuml.com/use-case-diagram
left to right direction

actor User
package "Account administration" {
  note "≪constraint≫ on all\nUser must be account owner OR admin" as appliesToAll

  usecase userAdminEmail as ([list | add | rm] email)
  User --> userAdminEmail: if User Account
  note right of userAdminEmail
    ' TODO
    ≪constraint≫
    add email: requires
    emailed activation
  end note

  usecase userAdminOrg as ([list | add | rm] org])
  User --> userAdminOrg: if User Account
  note right of userAdminOrg
    ≪constraint≫
    add org: org
    must not exist
  end note
  note right of userAdminOrg
    ≪constraint≫
    remove org: cascade all
    timesheets and projects
  end note
  usecase orgAdmin as ([list | add | rm] org admin)
  User --> orgAdmin: if Organisation Account
  note right of orgAdmin
    ≪constraint≫
    cannot remove
    User as admin
  end note

  usecase ownedAdmin as ([list | add | rm] [project | timesheet])
  User --> ownedAdmin
  note right of ownedAdmin
    ≪trigger≫
    add timesheet: init
    ts domain as genesis
  end note
  note right of ownedAdmin
    ≪constraint≫
    add: owned @id
    must have account
  end note
  note right of ownedAdmin
    ≪constraint≫
    owned is //composition//,
    cascade create & delete
    of account property
  end note
  note right of ownedAdmin
    ≪constraint≫
    timesheet provider is account
    project client is account
  end note

  User --> ([list | add | rm] timesheet project link)
  note right
    ≪constraint≫
    project must exist
  end note

  usecase integrations as ([list | add | rm] ts or project integration)
  User --> integrations
  note right of integrations
    ≪constraint≫
    timesheet or project must exist
  end note
  note right of integrations
    ≪trigger≫
    garbage collect integration
    stored data
  end note

  ' TODO
  User --> (revoke all device access)
  note right
    saves having to track
    devices individually.
    Followed by re-activate
    of current device
  end note
}

@enduml