@startuml
'https://plantuml.com/class-diagram

package ts {
    class Timesheet {
        entry : Entry
        project : Project [*]
    }

    class Entry {
        activity : xsd:string
        hourlyRate : hourlyRate
        contributor : vf:Provider
        startTime : xsd:dateTime
        duration: om2:Duration
        timesheet : Timesheet
    }

    note right of Entry::hourlyRate
        hourlyRate still
        to be elaborated
    end note

    note right of Entry::duration
        entry's duration property is also
        a sub-property of vf:effortQuantity
    end note

    Entry --|> "vf:Action"

        "Entry" "*" --* Timesheet

    class Project {
        startDate : xsd:dateTime
        duration : om2:Duration
        milestone : xsd:string
        client : Client [0..1]
    }

    Timesheet "*" -- "*" Project

    class Client {
        name : xsd:string
    }

    Project "*" -- "0..1" Client

    note as N1
    Project's client property is also
    a sub-property of vf:receiver
    end note

    N1 .. Project
    N1 .. Client

    Client --|> "foaf:Agent"

}

@enduml